==2621== Memcheck, a memory error detector
==2621== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==2621== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==2621== Command: ./uriProc
==2621== 
==2621== Invalid write of size 1
==2621==    at 0x40566F: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==  Address 0x5d0243b is 20 bytes after a block of size 7 alloc'd
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x405638: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== Invalid write of size 1
==2621==    at 0x4057DC: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:373)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x40576A: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== Invalid read of size 1
==2621==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2621==    by 0x55D23D8: printf (printf.c:33)
==2621==    by 0x4063D5: up_show(uri_proc_struct*) (uri_proc.c:775)
==2621==    by 0x406717: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:90)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x40576A: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== Conditional jump or move depends on uninitialised value(s)
==2621==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2621==    by 0x55D23D8: printf (printf.c:33)
==2621==    by 0x40636F: up_show(uri_proc_struct*) (uri_proc.c:771)
==2621==    by 0x40691D: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:106)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==  Uninitialised value was created by a heap allocation
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x405F2C: up_create_from_host(char*, int, void*) (uri_proc.c:610)
==2621==    by 0x406833: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x41481C: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== Invalid write of size 1
==2621==    at 0x40566F: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2621==    by 0x405F9D: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2621==    by 0x406833: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x41481C: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==  Address 0x5dd21a4 is 13 bytes after a block of size 7 alloc'd
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x405638: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2621==    by 0x405F9D: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2621==    by 0x406833: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40F3E7: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x415B92: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x42FCC1: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x4295FD: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== 
==2621== HEAP SUMMARY:
==2621==     in use at exit: 77,944 bytes in 263 blocks
==2621==   total heap usage: 51,309 allocs, 51,046 frees, 1,280,737 bytes allocated
==2621== 
==2621== 140 bytes in 7 blocks are still reachable in loss record 1 of 3
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2621==    by 0x40530A: _up_is_top_domain(char*, int, int) (uri_proc.c:205)
==2621==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2621==    by 0x405737: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== 5,100 bytes in 255 blocks are still reachable in loss record 2 of 3
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2621==    by 0x40529C: _up_is_top_domain(char*, int, int) (uri_proc.c:194)
==2621==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2621==    by 0x405737: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2621==    by 0x405D5A: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2621==    by 0x405E4C: up_create(char*, int, void*) (uri_proc.c:582)
==2621==    by 0x40662D: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2621==    by 0x42E8CB: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x428897: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40E4CA: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621==    by 0x40ED56: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2621== 
==2621== 72,704 bytes in 1 blocks are still reachable in loss record 3 of 3
==2621==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2621==    by 0x50BB62F: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22)
==2621==    by 0x4010109: call_init.part.0 (dl-init.c:78)
==2621==    by 0x40101F2: call_init (dl-init.c:36)
==2621==    by 0x40101F2: _dl_init (dl-init.c:126)
==2621==    by 0x4001309: ??? (in /lib/x86_64-linux-gnu/ld-2.19.so)
==2621== 
==2621== LEAK SUMMARY:
==2621==    definitely lost: 0 bytes in 0 blocks
==2621==    indirectly lost: 0 bytes in 0 blocks
==2621==      possibly lost: 0 bytes in 0 blocks
==2621==    still reachable: 77,944 bytes in 263 blocks
==2621==         suppressed: 0 bytes in 0 blocks
==2621== 
==2621== For counts of detected and suppressed errors, rerun with: -v
==2621== ERROR SUMMARY: 6319 errors from 5 contexts (suppressed: 0 from 0)
