==2608== Memcheck, a memory error detector
==2608== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==2608== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==2608== Command: ./uriProc
==2608== 
==2608== Invalid write of size 1
==2608==    at 0x405663: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==  Address 0x5d0243b is 20 bytes after a block of size 7 alloc'd
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x40562C: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== Invalid write of size 1
==2608==    at 0x4057D0: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:373)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x40575E: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== Invalid read of size 1
==2608==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2608==    by 0x55D23D8: printf (printf.c:33)
==2608==    by 0x4063C9: up_show(uri_proc_struct*) (uri_proc.c:775)
==2608==    by 0x40670B: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:90)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x40575E: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== Conditional jump or move depends on uninitialised value(s)
==2608==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2608==    by 0x55D23D8: printf (printf.c:33)
==2608==    by 0x406363: up_show(uri_proc_struct*) (uri_proc.c:771)
==2608==    by 0x406911: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:106)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==  Uninitialised value was created by a heap allocation
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405F20: up_create_from_host(char*, int, void*) (uri_proc.c:610)
==2608==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x414810: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== Invalid write of size 1
==2608==    at 0x405663: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2608==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2608==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x414810: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==  Address 0x5dd21a4 is 13 bytes after a block of size 7 alloc'd
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x40562C: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2608==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2608==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x4295F1: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 
==2608== HEAP SUMMARY:
==2608==     in use at exit: 106,864 bytes in 6,592 blocks
==2608==   total heap usage: 51,309 allocs, 44,717 frees, 1,280,737 bytes allocated
==2608== 
==2608== 4 bytes in 1 blocks are definitely lost in loss record 1 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2608==    by 0x4054EE: _up_get_top_level_index(char*, int, int) (uri_proc.c:273)
==2608==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 116 bytes in 30 blocks are definitely lost in loss record 2 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2608==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 140 bytes in 7 blocks are still reachable in loss record 3 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2608==    by 0x40530A: _up_is_top_domain(char*, int, int) (uri_proc.c:205)
==2608==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2608==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 5,100 bytes in 255 blocks are still reachable in loss record 4 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2608==    by 0x40529C: _up_is_top_domain(char*, int, int) (uri_proc.c:194)
==2608==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2608==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2608==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2608==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2608==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:87)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 28,800 bytes in 6,298 blocks are definitely lost in loss record 5 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2608==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2608==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2608==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:103)
==2608==    by 0x42E8BF: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42888B: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40E4BE: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40ED4A: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x40F3DB: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x415B86: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608==    by 0x42FCB5: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2608== 
==2608== 72,704 bytes in 1 blocks are still reachable in loss record 6 of 6
==2608==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2608==    by 0x50BB62F: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22)
==2608==    by 0x4010109: call_init.part.0 (dl-init.c:78)
==2608==    by 0x40101F2: call_init (dl-init.c:36)
==2608==    by 0x40101F2: _dl_init (dl-init.c:126)
==2608==    by 0x4001309: ??? (in /lib/x86_64-linux-gnu/ld-2.19.so)
==2608== 
==2608== LEAK SUMMARY:
==2608==    definitely lost: 28,920 bytes in 6,329 blocks
==2608==    indirectly lost: 0 bytes in 0 blocks
==2608==      possibly lost: 0 bytes in 0 blocks
==2608==    still reachable: 77,944 bytes in 263 blocks
==2608==         suppressed: 0 bytes in 0 blocks
==2608== 
==2608== For counts of detected and suppressed errors, rerun with: -v
==2608== ERROR SUMMARY: 6322 errors from 8 contexts (suppressed: 0 from 0)
